services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzCampaignBundle\Controller\FrontController:
        public: true
        arguments:
            $viewType: '$campaign_view;edgar_ez_campaign$'
