parameters:
    edgar_ez_campaign.default.campaign_view: 'campaign'
    edgar_ez_campaign.default.pagination.campaign_limit: 10
    edgar_ez_campaign.default.pagination.list_limit: 10
    edgar_ez_campaign.default.pagination.report_limit: 10
