services:
    Edgar\EzCampaign\FieldType\Campaign\Type:
        parent: ezpublish.fieldType
        arguments:
            $campaignsService: '@Edgar\EzCampaignBundle\Service\CampaignsService'
        tags:
            - {name: ezpublish.fieldType, alias: edgarcampaign}

    Edgar\EzCampaign\FieldType\Mapper\CampaignFormMapper:
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: edgarcampaign }
            - { name: ez.fieldFormMapper.value, fieldType: edgarcampaign }
