services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzCampaign\Form\Type\FieldType\CampaignFieldType: ~

    Edgar\EzCampaign\Persistence\Legacy\Content\FieldValue\Converter\CampaignConverter:
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: edgarcampaign}
