services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Edgar\EzCampaign\Menu\Admin\Campaign\CampaignCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: edgar.menu.campaign_create.sidebar_right }

    Edgar\EzCampaign\Menu\Admin\Campaign\ListCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: edgar.menu.list_create.sidebar_right }

    Edgar\EzCampaign\Menu\Admin\Campaign\CampaignEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: edgar.menu.campaign_edit.sidebar_right }

    Edgar\EzCampaign\Menu\Admin\Campaign\ListEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: edgar.menu.list_edit.sidebar_right }
