edgar.campaign.campaign.bulk_delete:
    path: /campaigns/delete
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:bulkDelete" }

edgar.campaign.campaigns:
    path: /campaigns/{folderId}
    methods: ['GET']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:campaigns", folderId: ~ }
    requirements:
        folderId: "[0-9a-z]+"

edgar.campaign.lists:
    path: /lists
    methods: ['GET']
    defaults: { _controller: "EdgarEzCampaignBundle:List:lists" }

edgar.campaign.reports:
    path: /reports/{campaignId}/{tabId}
    methods: ['GET']
    defaults: { _controller: "EdgarEzCampaignBundle:Reports:view", campaignId: ~, tabId: ~ }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.folder.bulk_delete:
    path: /folders/delete
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Folder:bulkDelete" }

edgar.campaign.list.bulk_delete:
    path: /lists/delete
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:List:bulkDelete" }

edgar.campaign.campaign.create:
    path: /campaign/create
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:create" }

edgar.campaign.folder.create:
    path: /folder/create
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Folder:create" }

edgar.campaign.list.create:
    path: /list/create
    defaults: { _controller: "EdgarEzCampaignBundle:List:create" }

edgar.campaign.campaign.edit:
    path: /campaign/edit/{campaignId}
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:edit" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.list.edit:
    path: /list/edit/{listId}
    defaults: { _controller: "EdgarEzCampaignBundle:List:edit" }
    requirements:
        listId: "[0-9a-z]+"

edgar.campaign.campaign.delete:
    path: /campaign/delete/{campaignId}
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:delete" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.campaign.view:
    path: /campaign/{campaignId}
    methods: ['GET']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:view" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.list.delete:
    path: /list/delete/{listId}
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:List:delete" }
    requirements:
        listId: "[0-9a-z]+"

edgar.campaign.list.view:
    path: /list/{listId}
    methods: ['GET']
    defaults: { _controller: "EdgarEzCampaignBundle:List:view" }
    requirements:
        listId: "[0-9a-z]+"

edgar.campaign.send:
    path: /canpaign/send/{campaignId}
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:send" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.schedule:
    path: /canpaign/schedule/{campaignId}
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:schedule" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.cancel.schedule:
    path: /canpaign/schedule/cancel/{campaignId}
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:cancelSchedule" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.create_content:
    path: /canpaign/content/create/{campaignId}
    methods: ['POST']
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:createContent" }
    requirements:
        campaignId: "[0-9a-z]+"

edgar.campaign.content:
    path: /canpaign/content/{campaignId}
    defaults: { _controller: "EdgarEzCampaignBundle:Campaign:content" }
    requirements:
        campaignId: "[0-9a-z]+"

