imports:
    - { resource: controllers.yml }
    - { resource: menu.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzCampaignBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    Edgar\EzCampaign\Form\Type\Field\ListType: ~
    Edgar\EzCampaign\Form\Type\Field\FolderType: ~
