imports:
    - { resource: controllers_ui.yml }
    - { resource: controllers.yml }
    - { resource: menu.yml }
    - { resource: tabs.yml }
    - { resource: slots.yml }

parameters:
    edgar.ezcampaign.param_converter.campaign.priority: 0
    edgar.ezcampaign.param_converter.list.priority: 0
    edgar.ezcampaign.param_converter.folder.priority: 0

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzCampaignBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    Edgar\EzCampaignBundle\Service\CampaignsService: ~

    Edgar\EzCampaign\Form\Type\Field\ListType: ~
    Edgar\EzCampaign\Form\Type\Field\FolderType: ~
    Edgar\EzCampaign\Form\Type\Field\CampaignsType: ~
    Edgar\EzCampaign\Form\Type\Field\FoldersType: ~
    Edgar\EzCampaign\Form\Type\Field\LanguageType: ~

    Edgar\EzCampaignBundle\Converter\CampaignParamConverter:
        tags:
            - { name: request.param_converter, priority: "%edgar.ezcampaign.param_converter.campaign.priority%", converter: edgarez_campaign_converter }

    Edgar\EzCampaignBundle\Converter\ListParamConverter:
        tags:
            - { name: request.param_converter, priority: "%edgar.ezcampaign.param_converter.list.priority%", converter: edgarez_list_converter }

    Edgar\EzCampaignBundle\Converter\FolderParamConverter:
        tags:
            - { name: request.param_converter, priority: "%edgar.ezcampaign.param_converter.folder.priority%", converter: edgarez_folder_converter }
